### ISSUE TITLE
There is no "core framework" for the project!

### ISSUE THREAD

**Issue by hanyaping** [ipfs-shipyard/gomobile-ipfs#45]
I can't find this “Core.framework”！！！

Where can I download it “Core.framework”？？？

Please reply me, thank you**

<img width="708" alt="22222" src="https://user-images.githubusercontent.com/17908865/89154014-ae0c2c00-d598-11ea-917e-8587fe227180.png">
<img width="563" alt="11111" src="https://user-images.githubusercontent.com/17908865/89154018-b06e8600-d598-11ea-8d6c-4d22dbeef14f.png">

**Comment by aeddi** [comment]
Hello,

You first have to go in the `packages` directory and run `make build_core.ios`.

**Comment by hanyaping** [comment]
我进入到了packages这个目录，然后输入了make build_core.ios 然后按回车键，提示我“make: /utils/manifest_get/manifest_get.sh: Command not found”

请问这是什么问题？ 是我电脑环境的问题吗？

hanMacBook-Pro:packages digaoao$ make build_core.ios
usage: dirname path
make: /utils/manifest_get/manifest_get.sh: Command not found
Makefile:34: *** "Can't get <global.group_id> from Manifest.yml".  Stop.


<img width="693" alt="WeChatf25102b1d7f2b4cb46db54ca13852f83" src="https://user-images.githubusercontent.com/17908865/90488562-accd2880-e16e-11ea-80e5-488c0e7c4a5e.png">
<img width="906" alt="WeChatff54a6909632d9bc56a92f701636808b" src="https://user-images.githubusercontent.com/17908865/90488578-b3f43680-e16e-11ea-935f-e27929433888.png">
<img width="574" alt="WeChat1699bca993ffedc8cbb619722e535bbc" src="https://user-images.githubusercontent.com/17908865/90488596-bb1b4480-e16e-11ea-9533-7ba877f307a7.png">

**Comment by aeddi** [comment]
Sorry I don't speak Chinese, please write in English so that we can understand each other (by the way, I'm French and I make the effort to speak English myself).

That said, thanks to your screenshots, I can see that the problem seems to be in your case, that the `MAKEFILE_DIR` variable of the Makefile is empty because there is a problem with this command: `$(realpath $(lastword $(MAKEFILE_LIST)))` and `dirname` doesn't get the right number of parameters (`usage: dirname path`).

I don't know what can cause this problem, maybe a too old version of make?

**Comment by aeddi** [comment]
Ok I think that's because there is a space in you path.
I'll see if I can take care of this problem when I have time.

But anyway for the compilation with gomobile to go well I advise you to `git clone` the repo in your `$GOPATH/src/github.com`.
